version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    working_directory: /tmp
    steps:
      - run:
          name: Install prerequisites
          command: gem install codeinventory && gem install codeinventory-github
      - run:
          name: Collect repository metadata
          command: /tmp/harvest.sh code.json
      - store_artifacts:
          path: /tmp/code.json

workflows:
  version: 2
  harvest:
    jobs:
      - build
